import { Rock, SubRock } from './store'

const generateId = () => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)

// ============================================================================
// 10 ROCKS - EOS Q4 2024 - Q1 2025
// ============================================================================

const rock1Id = generateId()
const rock2Id = generateId()
const rock3Id = generateId()
const rock4Id = generateId()
const rock5Id = generateId()
const rock6Id = generateId()
const rock7Id = generateId()
const rock8Id = generateId()
const rock9Id = generateId()
const rock10Id = generateId()

export const initialRocks: Rock[] = [
  // ============================================================================
  // ROCK 1: Modern Amenities - Sales Enablement ✅ COMPLETE
  // ============================================================================
  {
    id: rock1Id,
    name: 'MA: Sales Enablement',
    description: 'Build 5 sales enablement tools - COMPLETE',
    icon: '✅',
    color: '#8b5cf6', // purple for complete
    target: 'Achieve overall close rate ≥20% in December 2024',
    targetDate: '2024-12-31',
    progress: 100,
    status: 'complete',
    category: 'Modern Amenities',
    positionX: 100,
    positionY: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 2: Modern Amenities - Lead Generation
  // ============================================================================
  {
    id: rock2Id,
    name: 'MA: Lead Generation',
    description: 'Vendingpreneurs + AIMS lead gen program',
    icon: '📞',
    color: '#3b82f6', // blue
    target: '≥80% of Platinum students placed within 90 days (cohorts starting Oct 1+)',
    targetDate: '2024-12-31',
    progress: 45,
    status: 'in_progress',
    category: 'Modern Amenities',
    positionX: 100,
    positionY: 300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 3: Modern Amenities - Know Our Numbers
  // ============================================================================
  {
    id: rock3Id,
    name: 'MA: Know Our Numbers',
    description: 'Client-facing dashboards for all key metrics',
    icon: '📊',
    color: '#10b981', // green
    target: '5 client-facing dashboard templates published by Dec 31, 2024',
    targetDate: '2024-12-31',
    progress: 60,
    status: 'on_track',
    category: 'Modern Amenities',
    positionX: 100,
    positionY: 500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 4: Modern Amenities - Intern Project
  // ============================================================================
  {
    id: rock4Id,
    name: 'MA: Intern-Led Project',
    description: 'Scale-ready intern project system',
    icon: '🎓',
    color: '#f59e0b', // amber
    target: '1 intern-led project completed by Dec 20, 2024',
    targetDate: '2024-12-20',
    progress: 40,
    status: 'on_track',
    category: 'Modern Amenities',
    positionX: 100,
    positionY: 700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 5: AIMS - AI Agency to $50k/mo
  // ============================================================================
  {
    id: rock5Id,
    name: 'AIMS: AI Agency $50k/mo',
    description: 'Launch and scale AI agency to $50k MRR',
    icon: '🚀',
    color: '#ec4899', // pink
    target: '$50k MRR by February 2025',
    targetDate: '2025-02-28',
    progress: 25,
    status: 'in_progress',
    category: 'AIMS',
    positionX: 500,
    positionY: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 6: AIMS - Head of AI Position
  // ============================================================================
  {
    id: rock6Id,
    name: 'AIMS: Head of AI',
    description: 'Secure Head of AI role with team',
    icon: '👑',
    color: '#8b5cf6', // purple
    target: 'Role confirmation with $100k+ compensation by Q1 2025',
    targetDate: '2025-03-31',
    progress: 35,
    status: 'on_track',
    category: 'AIMS',
    positionX: 500,
    positionY: 300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 7: Accordant Capital - George Partnership
  // ============================================================================
  {
    id: rock7Id,
    name: 'Accordant Capital',
    description: 'George partnership & Chicago trip',
    icon: '💰',
    color: '#06b6d4', // cyan
    target: 'Complete website delivery + secure Chicago trip Q1 2025',
    targetDate: '2025-03-31',
    progress: 50,
    status: 'on_track',
    category: 'Accordant Capital',
    positionX: 500,
    positionY: 500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 8: DevSwarm - Growth Program
  // ============================================================================
  {
    id: rock8Id,
    name: 'DevSwarm: Growth Program',
    description: 'Multi-university growth intern program',
    icon: '💻',
    color: '#10b981', // green
    target: '1000+ signups by end of Q1 2025',
    targetDate: '2025-03-31',
    progress: 20,
    status: 'in_progress',
    category: 'DevSwarm',
    positionX: 500,
    positionY: 700,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 9: UO Foundation - AI Implementation
  // ============================================================================
  {
    id: rock9Id,
    name: 'UO Foundation',
    description: 'AI implementation project',
    icon: '🏛️',
    color: '#6366f1', // indigo
    target: 'Complete implementation by December 31, 2024',
    targetDate: '2024-12-31',
    progress: 15,
    status: 'not_started',
    category: 'UO Foundation',
    positionX: 900,
    positionY: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 10: Personal Systems - Second Brain
  // ============================================================================
  {
    id: rock10Id,
    name: 'Personal Systems',
    description: 'Full context productivity system',
    icon: '🧠',
    color: '#f59e0b', // amber
    target: 'Operational by December 1, 2024',
    targetDate: '2024-12-01',
    progress: 70,
    status: 'on_track',
    category: 'Personal',
    positionX: 900,
    positionY: 300,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// ============================================================================
// SUB-ROCKS FOR EACH ROCK
// ============================================================================

export const initialSubRocks: SubRock[] = [
  // ============================================================================
  // ROCK 2 SUB-ROCKS: Lead Generation
  // ============================================================================
  {
    id: generateId(),
    rockId: rock2Id,
    name: 'Cold-call certification in Second Nature',
    description: 'Complete certification program for all cold callers',
    target: 'All team members certified by Dec 15',
    targetDate: '2024-12-15',
    progress: 60,
    status: 'in_progress',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock2Id,
    name: 'CRMpros massive lead gen acceleration',
    description: 'Work with CRMpros to accelerate platinum student placements',
    target: 'CRMpros delivering 50+ leads/week',
    targetDate: '2024-12-31',
    progress: 30,
    status: 'at_risk',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock2Id,
    name: 'Thomas partnership: recycle old leads',
    description: 'Partner with Thomas to recycle old platinum student leads',
    target: 'Reactivate 100+ old leads',
    targetDate: '2024-12-31',
    progress: 40,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock2Id,
    name: 'Location tracking scorecards',
    description: 'Build scorecards of top performing vendingpreneur locations',
    target: 'Scorecards for top 20 locations',
    targetDate: '2024-12-31',
    progress: 50,
    status: 'on_track',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock2Id,
    name: 'Canteen competitor scraping',
    description: 'Scrape Canteen locations and send to cold call team',
    target: 'Scrape 500+ Canteen locations',
    targetDate: '2024-12-31',
    progress: 45,
    status: 'on_track',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 3 SUB-ROCKS: Know Our Numbers
  // ============================================================================
  {
    id: generateId(),
    rockId: rock3Id,
    name: 'Vendingpreneurs dashboard templates',
    description: 'Student Placement & Pipeline dashboards',
    target: '2 dashboard templates with pre-wired data',
    targetDate: '2024-12-31',
    progress: 70,
    status: 'on_track',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock3Id,
    name: 'Modern Amenities RevOps dashboard',
    description: 'Internal revenue operations dashboard',
    target: '1 comprehensive RevOps dashboard',
    targetDate: '2024-12-31',
    progress: 55,
    status: 'on_track',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock3Id,
    name: '3 AIMS client dashboards (ROI & QBR)',
    description: 'Client-facing ROI and QBR dashboards for AIMS',
    target: '3 client dashboard templates',
    targetDate: '2024-12-31',
    progress: 50,
    status: 'on_track',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock3Id,
    name: 'Write Spin-Up SOP',
    description: 'Standard operating procedure for Spin-Up process',
    target: 'Complete SOP with screenshots',
    targetDate: '2024-12-31',
    progress: 65,
    status: 'on_track',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock3Id,
    name: 'Record Loom walkthroughs',
    description: 'Video tutorials for each dashboard template',
    target: '5 Loom videos recorded',
    targetDate: '2024-12-31',
    progress: 60,
    status: 'on_track',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 4 SUB-ROCKS: Intern Project
  // ============================================================================
  {
    id: generateId(),
    rockId: rock4Id,
    name: 'Ship Database project MVP',
    description: 'Launch minimum viable database project',
    target: 'MVP deployed by EOY',
    targetDate: '2024-12-31',
    progress: 50,
    status: 'on_track',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock4Id,
    name: 'Build pipeline for scaling intern projects',
    description: 'Create repeatable system for intern-led projects',
    target: 'Pipeline framework documented',
    targetDate: '2024-12-20',
    progress: 35,
    status: 'in_progress',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock4Id,
    name: 'Produce Q1 scale plan',
    description: 'Capacity, automation, KPIs, cadence for Q1',
    target: 'Complete Q1 scale plan document',
    targetDate: '2024-12-20',
    progress: 30,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 5 SUB-ROCKS: AI Agency $50k/mo
  // ============================================================================
  {
    id: generateId(),
    rockId: rock5Id,
    name: 'Professional website update on Framer',
    description: 'Update website with case studies and portfolio',
    target: 'Website live with 3+ case studies',
    targetDate: '2025-01-31',
    progress: 40,
    status: 'in_progress',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock5Id,
    name: 'CRM Pros snapshot integration',
    description: 'Get access to CRM Pros snapshots for GHL',
    target: 'Snapshots integrated and tested',
    targetDate: '2025-01-15',
    progress: 20,
    status: 'in_progress',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock5Id,
    name: 'Snee/CloserX partnership execution',
    description: 'Partner with Snee for Agency Rewind resources',
    target: 'Partnership agreement signed',
    targetDate: '2024-12-31',
    progress: 15,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock5Id,
    name: 'GHL agency account setup',
    description: 'Get GHL agency account with snapshots from Snee',
    target: 'Agency account fully configured',
    targetDate: '2025-01-15',
    progress: 10,
    status: 'not_started',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock5Id,
    name: 'Build proprietary tool library',
    description: 'Create tools to exchange value with partners',
    target: '5 proprietary tools built',
    targetDate: '2025-02-15',
    progress: 30,
    status: 'in_progress',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 6 SUB-ROCKS: Head of AI
  // ============================================================================
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Onboard & manage Sheenam (SEO)',
    description: 'Fully onboard Sheenam for SEO work',
    target: 'Sheenam delivering weekly SEO tasks',
    targetDate: '2024-12-31',
    progress: 60,
    status: 'on_track',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Onboard & manage Sabbir (GHL)',
    description: 'Fully onboard Sabbir for GHL work',
    target: 'Sabbir delivering weekly GHL builds',
    targetDate: '2024-12-31',
    progress: 50,
    status: 'on_track',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Onboard & manage Maureen (RevOps)',
    description: 'Fully onboard Maureen for RevOps work',
    target: 'Maureen managing RevOps dashboards',
    targetDate: '2024-12-31',
    progress: 45,
    status: 'on_track',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Hire Clay expert (lead gen)',
    description: 'Recruit and onboard Clay automation expert',
    target: 'Clay expert hired and delivering',
    targetDate: '2025-01-15',
    progress: 20,
    status: 'in_progress',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Hire n8n expert (automation)',
    description: 'Recruit and onboard n8n automation expert',
    target: 'n8n expert hired and delivering',
    targetDate: '2025-01-15',
    progress: 15,
    status: 'not_started',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Hire campaign manager',
    description: 'Recruit and onboard campaign manager',
    target: 'Campaign manager hired and delivering',
    targetDate: '2025-01-31',
    progress: 10,
    status: 'not_started',
    order: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Crush Q4 Modern Amenities rocks',
    description: 'Complete all Q4 MA rocks to prove leadership capability',
    target: 'All Q4 rocks at 90%+ progress',
    targetDate: '2024-12-31',
    progress: 50,
    status: 'on_track',
    order: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock6Id,
    name: 'Build AIMS revenue case',
    description: 'Document direct revenue contribution to AIMS',
    target: 'Revenue case deck complete',
    targetDate: '2025-02-28',
    progress: 25,
    status: 'in_progress',
    order: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 7 SUB-ROCKS: Accordant Capital
  // ============================================================================
  {
    id: generateId(),
    rockId: rock7Id,
    name: 'Deliver multifamily portfolio website',
    description: 'Complete Accordant Capital website build',
    target: 'Website live and approved',
    targetDate: '2024-12-31',
    progress: 75,
    status: 'on_track',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock7Id,
    name: 'Monthly value-adds to George',
    description: 'Deliver AI insights and value monthly',
    target: 'Monthly check-ins with value delivery',
    targetDate: '2025-03-31',
    progress: 40,
    status: 'on_track',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock7Id,
    name: 'Secure personal development plan',
    description: 'Get George to commit to PDP',
    target: 'PDP framework agreed',
    targetDate: '2025-01-31',
    progress: 30,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock7Id,
    name: 'Schedule Chicago networking trip',
    description: 'Get Chicago trip scheduled with key introductions',
    target: 'Trip scheduled with agenda',
    targetDate: '2025-03-31',
    progress: 20,
    status: 'in_progress',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 8 SUB-ROCKS: DevSwarm Growth Program
  // ============================================================================
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Build scalable growth intern program structure',
    description: 'Create framework for growth intern program',
    target: 'Program framework documented',
    targetDate: '2024-12-31',
    progress: 35,
    status: 'in_progress',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Hire growth interns across universities',
    description: 'Recruit growth interns at multiple schools',
    target: '10 growth interns hired',
    targetDate: '2025-01-31',
    progress: 25,
    status: 'in_progress',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Create playbook templates for interns',
    description: 'Build playbooks for intern execution',
    target: '5 playbook templates ready',
    targetDate: '2024-12-31',
    progress: 30,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Launch webinar series with Mike',
    description: 'Host webinars featuring growth interns',
    target: '2 webinars completed',
    targetDate: '2025-02-28',
    progress: 10,
    status: 'not_started',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Content creation system for viral growth',
    description: 'Build system to create viral content',
    target: 'Content system operational',
    targetDate: '2025-01-31',
    progress: 15,
    status: 'in_progress',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock8Id,
    name: 'Track metrics: signups, performance, reach',
    description: 'Build dashboard for tracking all growth metrics',
    target: 'Metrics dashboard live',
    targetDate: '2025-01-15',
    progress: 20,
    status: 'in_progress',
    order: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 9 SUB-ROCKS: UO Foundation
  // ============================================================================
  {
    id: generateId(),
    rockId: rock9Id,
    name: 'December scope meeting',
    description: 'Meet with UO Foundation to scope AI implementation',
    target: 'Scope meeting completed',
    targetDate: '2024-12-15',
    progress: 20,
    status: 'not_started',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock9Id,
    name: 'AI audit and recommendation deck',
    description: 'Audit current systems and provide AI recommendations',
    target: 'Deck delivered and approved',
    targetDate: '2024-12-22',
    progress: 10,
    status: 'not_started',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock9Id,
    name: 'Implementation sprint',
    description: 'Execute AI implementation',
    target: 'Implementation complete',
    targetDate: '2024-12-31',
    progress: 5,
    status: 'not_started',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock9Id,
    name: 'Training and handoff documentation',
    description: 'Train team and create handoff docs',
    target: 'Training complete, docs delivered',
    targetDate: '2024-12-31',
    progress: 0,
    status: 'not_started',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ============================================================================
  // ROCK 10 SUB-ROCKS: Personal Systems
  // ============================================================================
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Notion EOS workspace with all rocks tracked',
    description: 'Setup Notion workspace with EOS framework',
    target: 'Notion workspace operational',
    targetDate: '2024-12-01',
    progress: 80,
    status: 'on_track',
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Daily EOD reports with context capture',
    description: 'Build system for daily EOD reports',
    target: 'EOD system operational',
    targetDate: '2024-12-01',
    progress: 75,
    status: 'on_track',
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Granola.ai meeting notes auto-sync',
    description: 'Integrate Granola for automatic meeting notes',
    target: 'Granola integration live',
    targetDate: '2024-12-15',
    progress: 40,
    status: 'in_progress',
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Claude Code perpetual context system',
    description: 'Setup Claude Code with Basic Memory MCP',
    target: 'Claude never loses context',
    targetDate: '2024-12-01',
    progress: 85,
    status: 'on_track',
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Weekly reflection and journaling cadence',
    description: 'Establish weekly reflection routine',
    target: 'Weekly reflection habit established',
    targetDate: '2024-12-01',
    progress: 60,
    status: 'on_track',
    order: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Automated task prioritization based on rocks',
    description: 'Build system to auto-prioritize tasks by rock alignment',
    target: 'Auto-prioritization working',
    targetDate: '2024-12-15',
    progress: 55,
    status: 'on_track',
    order: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    rockId: rock10Id,
    name: 'Never-miss tracking for calls, tasks, insights',
    description: 'Ensure no information is lost from any interaction',
    target: '100% capture rate for 30 days',
    targetDate: '2024-12-31',
    progress: 70,
    status: 'on_track',
    order: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
